/**
 * Fetches book data from Google Books API by ISBN and appends to a generated constants file.
 *
 * Usage:
 *   npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/fetch-books.ts
 *
 * Edit the ISBNs array below before running.
 */

import * as fs from 'fs'
import * as path from 'path'
import * as https from 'https'
import { randomUUID } from 'crypto'

// ─── Configure ISBNs here ────────────────────────────────────────────────────
const ISBNS = [
  '9780743273565', // The Great Gatsby
  '9780061965579', // To Kill a Mockingbird
  '9780451524935', // 1984
  '9780316769174', // The Catcher in the Rye
  '9780062316097', // The Alchemist
  '9780385333481', // The Handmaid's Tale
  '9780679720201', // Crime and Punishment
  '9780486415871', // Pride and Prejudice
  '9780062409850', // Sapiens
  '9780385737951', // The Maze Runner
]
// ─────────────────────────────────────────────────────────────────────────────

const API_KEY = process.env.NEXT_PUBLIC_GOOGLE_BOOKS_API_KEY ?? ''
const OUTPUT_FILE = path.join(__dirname, 'constants', 'books-generated.ts')

const CATEGORY_MAP: Record<string, { name: string; id: string }> = {
  'science fiction': { name: 'Science Fiction', id: '8c4a4a4d-cbc4-4d2c-bb46-e95b0a536e09' },
  fantasy: { name: 'Fantasy', id: 'q1d50407-0aa7-4245-8a5c-0d0de14e9d6d' },
  fiction: { name: 'Fiction', id: 'f1a50507-0aa7-4245-8a5c-0d0de14e9d6d' },
  spirituality: { name: 'Spirituality', id: 'vf2a4a4d-cbc4-4d2c-bb46-e95b0a536e09' },
  classic: { name: 'Classic', id: 'd4c23017-4378-4e24-84a1-7e37f343dfc2' },
  thriller: { name: 'Thriller', id: 'h1n54207-0aa7-4245-8a5c-0d0de14e9d6d' },
  horror: { name: 'Horror', id: 'l7o22067-4978-4a24-84a1-7d37f343dfc2' },
  'young adult': { name: 'Young adult', id: 'w5f22067-4978-4f24-84a1-7d37f343dfc2' },
  autobiography: { name: 'Autobiography', id: 'm7fn22067-4978-4a24-84a1-7d37f343dfc2' },
  biography: { name: 'Autobiography', id: 'm7fn22067-4978-4a24-84a1-7d37f343dfc2' },
  'self-help': { name: 'Self-help', id: 'po922067-4978-4a24-84a1-7d37f343dfc2' },
  history: { name: 'History', id: 'c9f22067-4978-4a24-84a1-7d37f343dfc2' },
}

const DEFAULT_CATEGORY = { name: 'Fiction', id: 'f1a50507-0aa7-4245-8a5c-0d0de14e9d6d' }

function resolveCategories(subjects: string[]): { name: string; id: string }[] {
  const matched = new Map<string, { name: string; id: string }>()

  for (const subject of subjects) {
    const lower = subject.toLowerCase()
    for (const [key, category] of Object.entries(CATEGORY_MAP)) {
      if (lower.includes(key)) {
        matched.set(category.id, category)
      }
    }
  }

  return matched.size > 0 ? Array.from(matched.values()) : [DEFAULT_CATEGORY]
}

function get(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = ''
      res.on('data', (chunk) => (data += chunk))
      res.on('end', () => resolve(data))
      res.on('error', reject)
    }).on('error', reject)
  })
}

async function fetchBook(isbn: string) {
  const keyParam = API_KEY ? `&key=${API_KEY}` : ''
  const url = `https://www.googleapis.com/books/v1/volumes?q=isbn:${isbn}${keyParam}`
  const raw = await get(url)
  const json = JSON.parse(raw)

  if (!json.items?.length) {
    console.warn(`  [SKIP] No results for ISBN ${isbn}`)
    return null
  }

  const info = json.items[0].volumeInfo

  const coverUrl =
    `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`

  return {
    id: randomUUID(),
    name: info.title ?? 'Unknown',
    author: info.authors?.[0] ?? 'Unknown',
    summary: info.description ?? '',
    coverUrl,
    totalPages: info.pageCount ?? 0,
    publishingYear: info.publishedDate?.slice(0, 4) ?? null,
    publisher: info.publisher ?? null,
    language: info.language ?? 'en',
    isbn,
    status: 'APPROVED',
    categories: resolveCategories(info.categories ?? []),
  }
}

async function main() {
  console.log(`Fetching ${ISBNS.length} books from Google Books API...\n`)

  const results = []

  for (const isbn of ISBNS) {
    process.stdout.write(`  ISBN ${isbn} ... `)
    try {
      const book = await fetchBook(isbn)
      if (book) {
        results.push(book)
        console.log(`OK — "${book.name}"`)
      }
    } catch (err) {
      console.log(`ERROR — ${err}`)
    }

    // avoid hitting rate limits
    await new Promise((r) => setTimeout(r, 200))
  }

  const output = `// Auto-generated by prisma/fetch-books.ts — do not edit manually
export const generatedBooks = ${JSON.stringify(results, null, 2)}
`

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')
  console.log(`\nWrote ${results.length} books to ${OUTPUT_FILE}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
