// Auto-generated by prisma/fetch-books.ts — do not edit manually
export const generatedBooks = [
  {
    "id": "9408135d-0339-44c8-8bd0-e563e418cd76",
    "name": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "summary": "A mysterious American millionaire tries to recapture the sweetheart of his youth, which results in tragedy.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    "totalPages": 208,
    "publishingYear": "2004",
    "publisher": "Simon and Schuster",
    "language": "en",
    "isbn": "9780743273565",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "f4b6214a-7549-4f1c-a718-54411ca912f5",
    "name": "Leadership",
    "author": "James M. Burns",
    "summary": "Pulitzer Prize-winning historian James MacGregor Burns has devoted his legendary career to the study of leadership in all its aspects—from politics to business. Leadership, Burns's pioneering study, introduces the highly influential theory of \"transformational leadership,\" stating that the best leaders are those who inspire others to come together toward the achievement of higher aims. Featuring fascinating case studies drawn from history, Leadership is the classic text for anyone seeking to understand executive decision-making, the dynamics of influence, and moral leadership.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780061965579-L.jpg",
    "totalPages": 547,
    "publishingYear": "2010",
    "publisher": "Harper Collins",
    "language": "en",
    "isbn": "9780061965579",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "a0bd169f-a082-46f0-b9b9-493a5fc56bdc",
    "name": "Nineteen Eighty-four",
    "author": "George Orwell",
    "summary": "Eternal warfare is the price of bleak prosperity in this satire of totalitarian barbarism.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    "totalPages": 326,
    "publishingYear": "1949",
    "publisher": null,
    "language": "en",
    "isbn": "9780451524935",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "17c4bf8a-45a3-4d35-8223-f6498a67e00e",
    "name": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "summary": "J.D. Salinger's classic of adolescent angst is now available for the first time in trade paperback. Holden Caulfield, knowing he is to be expelled from school, decides to leave early. He spends three days in New York City and tells the story of what he did and suffered there.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
    "totalPages": 232,
    "publishingYear": "2001",
    "publisher": "Back Bay Books",
    "language": "en",
    "isbn": "9780316769174",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "b2e193bf-c238-4e42-bbd4-df6199bd0936",
    "name": "Sapiens",
    "author": "Yuval Noah Harari",
    "summary": "One hundred thousand years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance? Why did our foraging ancestors come together to create cities and kingdoms? How did we come to believe in gods, nations, and human rights; to trust money, books, and laws; and to be enslaved by bureaucracy, timetables, and consumerism? And what will our world be like in the millennia to come? In Sapiens, Professor Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical—and sometimes devastating—breakthroughs of the Cognitive, Agricultural, and Scientific Revolutions. Drawing on insights from biology, anthropology, paleontology, and economics, and incorporating full-color illustrations throughout the text, he explores how the currents of history have shaped our human societies, the animals and plants around us, and even our personalities. Have we become happier as history has unfolded? Can we ever free our behavior from the legacy of our ancestors? And what, if anything, can we do to influence the course of the centuries to come? Bold, wide-ranging, and provocative, Sapiens integrates history and science to challenge everything we thought we knew about being human: our thoughts, our actions, our heritage...and our future.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    "totalPages": 464,
    "publishingYear": "2015",
    "publisher": "Harper",
    "language": "en",
    "isbn": "9780062316097",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "43cb9964-dea5-4f02-8d7d-c8ae52c9d9f0",
    "name": "Cat's Cradle",
    "author": "Kurt Vonnegut",
    "summary": "“A free-wheeling vehicle . . . an unforgettable ride!”—The New York Times Cat’s Cradle is Kurt Vonnegut’s satirical commentary on modern man and his madness. An apocalyptic tale of this planet’s ultimate fate, it features a midget as the protagonist, a complete, original theology created by a calypso singer, and a vision of the future that is at once blackly fatalistic and hilariously funny. A book that left an indelible mark on an entire generation of readers, Cat’s Cradle is one of the twentieth century’s most important works—and Vonnegut at his very best. “[Vonnegut is] an unimitative and inimitable social satirist.”—Harper’s Magazine “Our finest black-humorist . . . We laugh in self-defense.”—Atlantic Monthly",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385333481-L.jpg",
    "totalPages": 308,
    "publishingYear": "1998",
    "publisher": "Dial Press Trade Paperback",
    "language": "en",
    "isbn": "9780385333481",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "fa6c33a5-5f94-4911-9e02-197039a83466",
    "name": "The Stranger",
    "author": "Albert Camus",
    "summary": "The masterpiece of Nobel Prize winner Albert Camus now in a striking American English translation. The Stranger remains vital for its unsettling insights into the impossibility of moral certainty in the face of violence. “Matthew Ward has done Camus and us a great service. The Stranger is now a different and better novel for its American readers; it is now our classic as well as France’s.”—Chicago Sun-Times Since it was first published in English, in 1946, Albert Camus’s first novel, The Stranger (L’etranger), has had a profound impact on millions of American readers. Through this story of an ordinary man who unwittingly gets drawn into a senseless murder on a sundrenched Algerian beach, Camus explored what he termed “the nakedness of man faced with the absurd.” Now, in this illuminating translation, extraordinary for its exactitude and clarity, the original intent of The Stranger is made more immediate. This haunting novel has been given a new life for generations to come.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg",
    "totalPages": 145,
    "publishingYear": "1989",
    "publisher": "Vintage",
    "language": "en",
    "isbn": "9780679720201",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "902fe6e0-78cd-4535-9eab-7dd2ef57e715",
    "name": "Crime and Punishment",
    "author": "Fyodor Dostoyevsky",
    "summary": "In a timeless story of justice, morality, and redemption, an impoverished Russian student murders a miserly landlady, a crime that has severe repercussions on his life and his family as he battles his conscience.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    "totalPages": 449,
    "publishingYear": "2001",
    "publisher": "Courier Corporation",
    "language": "en",
    "isbn": "9780486415871",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "279b9e6f-3ac3-4808-b402-91778a8e342c",
    "name": "Go Set a Watchman",
    "author": "Harper Lee",
    "summary": "An historic literary event: the publication of a newly discovered novel, the earliest known work from Harper Lee, the beloved, bestselling author of the Pulitzer Prize-winning classic, To Kill a Mockingbird. Originally written in the mid-1950s, Go Set a Watchman was the novel Harper Lee first submitted to her publishers before To Kill a Mockingbird. Assumed to have been lost, the manuscript was discovered in late 2014. Go Set a Watchman features many of the characters from To Kill a Mockingbird some twenty years later. Returning home to Maycomb to visit her father, Jean Louise Finch—Scout—struggles with issues both personal and political, involving Atticus, society, and the small Alabama town that shaped her. Exploring how the characters from To Kill a Mockingbird are adjusting to the turbulent events transforming mid-1950s America, Go Set a Watchman casts a fascinating new light on Harper Lee’s enduring classic. Moving, funny and compelling, it stands as a magnificent novel in its own right.",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780062409850-L.jpg",
    "totalPages": 288,
    "publishingYear": "2015",
    "publisher": "Harper",
    "language": "en",
    "isbn": "9780062409850",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      }
    ]
  },
  {
    "id": "a67b65c0-b555-4351-855c-923d1880a345",
    "name": "The Maze Runner",
    "author": "James Dashner",
    "summary": "THE #1 NEW YORK TIMES BESTSELLING MAZE RUNNER SERIES • A teenager with no memory must navigate a deadly maze to survive in book one of this post-apocalyptic phenomenon. “[A] mysterious survival saga that passionate fans describe as a fusion of Lord of the Flies [and] The Hunger Games” (Entertainment Weekly) When Thomas wakes up in the lift, the only thing he can remember is his name. He’s surrounded by strangers—boys whose memories are also gone. Outside the towering stone walls that surround them is a limitless, ever-changing maze. It’s the only way out—and no one’s ever made it through alive. Then a girl arrives. The first girl ever. And the message she delivers is terrifying: Remember. Survive. Run. Look for more books in the blockbuster Maze Runner series: THE MAZE RUNNER • THE SCORCH TRIALS • THE DEATH CURE • THE KILL ORDER • THE FEVER CODE",
    "coverUrl": "https://covers.openlibrary.org/b/isbn/9780385737951-L.jpg",
    "totalPages": 417,
    "publishingYear": "2010",
    "publisher": "Delacorte Press",
    "language": "en",
    "isbn": "9780385737951",
    "status": "APPROVED",
    "categories": [
      {
        "name": "Fiction",
        "id": "f1a50507-0aa7-4245-8a5c-0d0de14e9d6d"
      },
      {
        "name": "Young adult",
        "id": "w5f22067-4978-4f24-84a1-7d37f343dfc2"
      }
    ]
  }
]
